language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - gem install sass
  - npm install -g firebase-tools
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm build

after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}

notifications:
  slack: scvodigital:BPrM2dvC1icb0UHwglQ5DBfI
